+define+QUESTA
+incdir+QUESTA_HOME/include
+incdir+$QUESTA_HOME/verilog_src/uvm-1.2/src
+incdir+$QUESTA_HOME/verilog_src/uvm-1.2/src/dpi
+incdir+$VERDIR/unit_tb/qsfp_controller/vip/axi_vip/include/verilog
+incdir+$VERDIR/unit_tb/qsfp_controller/vip/axi_vip/include/sverilog
+incdir+$VERDIR/unit_tb/qsfp_controller/vip/axi_vip/src/verilog/mti
+incdir+$VERDIR/unit_tb/qsfp_controller/vip/axi_vip/src/sverilog/mti
+incdir+$VERDIR/unit_tb/qsfp_controller/vip/axi_vip/lib/linux64
+incdir+$VERDIR/unit_tb/qsfp_controller/tests/sequences
+incdir+$VERDIR/unit_tb/qsfp_controller/vip/axi_vip/include/verilog
+incdir+$VERDIR/unit_tb/qsfp_controller/vip/axi_vip/include/sverilog
+incdir+$VERDIR/unit_tb/qsfp_controller/vip/axi_vip/src/verilog/mti
+incdir+$VERDIR/unit_tb/qsfp_controller/vip/axi_vip/src/sverilog/mti
+incdir+$VERDIR/unit_tb/qsfp_controller/tests/sequences
+incdir+$VERDIR/unit_tb/qsfp_controller/tests
+incdir+$VERDIR/unit_tb/qsfp_controller/testbench
-L $QUESTA_HOME/uvm-1.2
//$QUESTA_HOME/include/svdpi.h
$QUESTA_HOME/verilog_src/uvm-1.2/src/uvm_pkg.sv
$QUESTA_HOME/verilog_src/uvm-1.2/src/uvm_macros.svh
//$QUESTA_HOME/verilog_src/uvm-1.2/src/dpi/uvm_dpi.cc 
$VERDIR/unit_tb/qsfp_controller/vip/axi_vip/src/sverilog/mti/svt_if_util.svi
$VERDIR/unit_tb/qsfp_controller/vip/axi_vip/include/sverilog/svt_gpio_if.svi
$VERDIR/unit_tb/qsfp_controller/vip/axi_vip/include/sverilog/svt.uvm.pkg
$VERDIR/unit_tb/qsfp_controller/vip/axi_vip/include/sverilog/svt_axi.uvm.pkg
$VERDIR/unit_tb/qsfp_controller/vip/axi_vip/include/sverilog/svt_axi_if.svi
$VERDIR/unit_tb/qsfp_controller/vip/axi_vip/include/sverilog/svt_axi_port_defines.svi
$VERDIR/unit_tb/qsfp_controller/vip/axi_vip/src/sverilog/mti/svt_env.sv
$VERDIR/unit_tb/qsfp_controller/vip/axi_vip/src/sverilog/mti/svt_axi_system_env.sv

